### ISSUE TITLE
Crash with max_workers > 2

### ISSUE THREAD

**Issue by Topvennie** [Topvennie/Online-Crowd-Analyzer#15]
If the max_works is set to a higher value than 2 and `MobileNetSSd` is used as a model then the centroid tracker crashes.

<details><summary>Logs</summary><pre>
```
/Online-Crowd-Analyzer/src/trackers/centroidtracker/centroidtracker.py:69: RuntimeWarning: invalid value encountered in scalar add
  cX = int((startX + endX) / 2.0)
Exception in thread Thread-2 (_track):
Traceback (most recent call last):
  File "/root/.asdf/installs/python/3.12.1/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/root/.asdf/installs/python/3.12.1/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Online-Crowd-Analyzer/src/counter.py", line 136, in _track
    objects = self._tracker.update(detections)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Online-Crowd-Analyzer/src/trackers/centroidtracker/centroidtracker.py", line 69, in update
    cX = int((startX + endX) / 2.0)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
```

**Comment by Topvennie** [comment]
This is because multiple threads executed this code at the same time

```py
blob = cv2.dnn.blobFromImage(frame, 0.007843, (300, 300), [127.5])
        self._model.setInput(blob)
        detections: NDArray[np.float32] = self._model.forward()  # type: ignore
```

This is fixable by adding a lock however adding a lock and increasing the `max_workers` didn't show any speed improvements (see #4 ). 
`max_workers` will be kept to 1 for the foreseeable future so no need to add the lock.
